name = "TOONBench"
uuid = "12345678-1234-1234-1234-123456789012"
authors = ["Tu Nombre <tuemail@ejemplo.com>"]
version = "0.1.0"

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[compat]
julia = "1.9"
PythonCall = "0.9"
DataFrames = "1"
JSON3 = "1"
BenchmarkTools = "1"